# .github/workflows/destroy.yml

name: 'Destroy Backend Infrastructure with Terraform'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm you want to permanently destroy all resources.'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    # Define the confirmation phrase as an environment variable for easy management
    env:
      CONFIRMATION_PHRASE: 'destroy'

    defaults:
      run:
        working-directory: ./backend/environments/dev

    steps:
      # This step explicitly checks the user's input before proceeding.
      # It will fail the entire workflow if the confirmation does not match.
      - name: 'Verify Destroy Confirmation'
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "${{ env.CONFIRMATION_PHRASE }}" ]; then
            echo "❌ ERROR: Confirmation phrase did not match. Aborting workflow."
            exit 1
          else
            echo "✅ Confirmation phrase matches. Proceeding with destroy operation."
          fi
        # This step does not need a working-directory
        working-directory: .

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        id: init
        run: terraform init -upgrade

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve